name: tests

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.crds_context }}
  cancel-in-progress: true

jobs:
  check:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v2
    with:
      envs: |
        - name: Check for Sphinx doc build errors
          linux: py311-docbuild
  retrieve_cache:
    uses: spacetelescope/stpsf/.github/workflows/retrieve_cache.yml@ee1ced313cc7277f07226f03e64d038f3929d7a3 # setup retrieve_cache with development or latest_release
    with:
      dataset_type: development   # or latest_release
  test:
    needs: [ retrieve_cache ]
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v2
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      setenv: |
        STPSF_PATH: ${{ needs.retrieve_cache.outputs.cache_path }}/stpsf-data/
      cache-path: ${{ needs.retrieve_cache.outputs.cache_path }}
      cache-key: ${{ needs.retrieve_cache.outputs.cache_key }}
      envs: |
        - name: Try minimum supported versions
          linux: py310-test-legacy
        - name: Coverage test in Python 3
          linux: py313-test-cov
        - name: Try Astropy development version
          linux: py314-test-astropydev
        - name: Try latest versions of all dependencies
          linux: py314-test-poppydev-pysiafdev
      fill: true
      fill_factors: test
